title: tqlmorepassion
description: > # this means to ignore newlines until "baseurl:"
  tqlmorepassion,夏雨荷她男人
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tqlmorepassion.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: 夏雨荷她男人 # 名字
author-img: head.png # 照片
about-author: Android Developer # add description
github: tqlmorepassion # add your Github handle
email: tqlmorepassion@foxmail.com
zhihu: tqlmorepassion
weibo: tqlmorepassion
jianshu: u/de6d5d54c98d

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
